# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /website
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: website
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web
#     traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd # <namespace-of-middlewear>-<name-of-middlewear>

# spec:
#   rules:
#     - http:
#         paths:
#           # TODO: make site accessible at the defined url path
#           - path: /website
#             pathType: Prefix
#             backend:
#               service:
#                 name: website-svc
#                 port:
#                   number: 8080
#           # - path: /
#           #   pathType: Exact
#           #   backend:
#           #     service:
#           #       name: website-svc
#           #       port:
#           #         number: 8080
